//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        public int TarjetaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string NumeroTarjeta { get; set; }
        public string TipoTarjeta { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<decimal> SaldoDisponible { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
