//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaResumenCliente
    {
        public int ClienteID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string TipoCuenta { get; set; }
        public Nullable<decimal> SaldoCuenta { get; set; }
        public Nullable<decimal> MontoPrestamo { get; set; }
        public Nullable<decimal> SaldoPendiente { get; set; }
    }
}
